apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: lana-yolo-hpa
  namespace: lanabot-dev-ns
  labels:
    microservice: lana-yolo
    project: lanabot-project
    env: dev
    release: v1.0
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lana-yolo-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
