apiVersion: apps/v1
kind: Deployment
metadata:
  name: lana-yolo-deployment
  namespace: lanabot-dev-ns
  labels:
    microservice: lana-yolo
    project: lanabot-project
    env: dev
    release: v1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      microservice: lana-yolo
  template:
    metadata:
      labels:
        microservice: lana-yolo
        project: lanabot-project
        env: dev
        release: v1.0
    spec:
      containers:
      - name: lana-yolo-docker-container
        image: lanayolo_img:tag
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 20

---

apiVersion: v1
kind: Service
metadata:
  name: lanayolo-service
  labels:
    project: lanabot-project
    env: dev
    release: v1.0
spec:
  selector:
    microservice: lana-yolo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

---

apiVersion: autoscaling/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: lana-yolo-hpa
  namespace: lanabot-dev-ns
  labels:
    microservice: lana-yolo
    project: lanabot-project
    env: dev
    release: v1.0
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lana-yolo-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50