apiVersion: v1
kind: Pod
metadata:
  name: lana-yolo-pod
  namespace: lanabot-dev-ns
  labels:
    project: lanabot-project
    env: dev
    release: v1.0
spec:
  containers:
  - name: lana-yolo-docker-container
    image: lanayolo_image:tag

