apiVersion: apps/v1
kind: Deployment
metadata:
  name: lana-yolo-deployment
  namespace: lanabot-ns
  labels:
    app: lana-yolo
    env: dev
    release: v1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lana-yolo
  template:
    metadata:
      labels:
        app: lana-yolo
        env: dev
        release: v1.0
    spec:
      containers:
      - name: lana-yolo-docker-container
        image: lanayolo_image:tag
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi