apiVersion: apps/v1
kind: Deployment
metadata:
  name: lana-yolo-deployment
  namespace: lanabot-dev-ns
  labels:
    microservice: lana-yolo
    project: lanabot-project
    env: dev
    release: v1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      microservice: lana-yolo
  template:
    metadata:
      labels:
        microservice: lana-yolo
        project: lanabot-project
        env: dev
        release: v1.0
    spec:
      containers:
      - name: lana-yolo-docker-container
        image: lanayolo_image:tag
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
